"""initial schema

Revision ID: c075f3db2113
Revises:
Create Date: 2026-05-07 15:16:34.900457

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c075f3db2113"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("operator_country", sa.CHAR(length=2), nullable=True),
        sa.Column("operator_name", sa.Text(), nullable=True),
        sa.Column(
            "operator_type",
            sa.Enum(
                "GOVERNMENT",
                "MILITARY",
                "COMMERCIAL",
                "INTERNATIONAL",
                name="operator_type",
            ),
            nullable=True,
        ),
        sa.Column(
            "orbit_class",
            sa.Enum("LEO", "MEO", "GEO", "HEO", name="orbit_class_type"),
            nullable=True,
        ),
        sa.Column("launch_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("norad_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "country_bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "country_code"),
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_user_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id"),
    )
    op.create_table(
        "passkey_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.Text(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id"),
    )
    op.create_table(
        "satellite_bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["satellite_id"], ["satellites.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "satellite_id"),
    )
    op.create_table(
        "tle_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("line1", sa.CHAR(length=69), nullable=False),
        sa.Column("line2", sa.CHAR(length=69), nullable=False),
        sa.Column("epoch", sa.DateTime(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["satellite_id"],
            ["satellites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tle_snapshots_satellite_ingested",
        "tle_snapshots",
        ["satellite_id", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "predicted_passes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("tle_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("entry_time", sa.DateTime(), nullable=False),
        sa.Column("exit_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("entry_lat", sa.Float(), nullable=True),
        sa.Column("entry_lon", sa.Float(), nullable=True),
        sa.Column("exit_lat", sa.Float(), nullable=True),
        sa.Column("exit_lon", sa.Float(), nullable=True),
        sa.Column("predicted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["satellite_id"],
            ["satellites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tle_snapshot_id"],
            ["tle_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_predicted_passes_country_entry",
        "predicted_passes",
        ["country_code", "entry_time"],
        unique=False,
    )
    op.create_index(
        "ix_predicted_passes_satellite_entry",
        "predicted_passes",
        ["satellite_id", "entry_time"],
        unique=False,
    )
    op.create_table(
        "actual_passes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("tle_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("entry_time", sa.DateTime(), nullable=False),
        sa.Column("exit_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("entry_lat", sa.Float(), nullable=True),
        sa.Column("entry_lon", sa.Float(), nullable=True),
        sa.Column("exit_lat", sa.Float(), nullable=True),
        sa.Column("exit_lon", sa.Float(), nullable=True),
        sa.Column("predicted_pass_id", sa.Integer(), nullable=True),
        sa.Column("anomaly_flag", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["predicted_pass_id"],
            ["predicted_passes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["satellite_id"],
            ["satellites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tle_snapshot_id"],
            ["tle_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_actual_passes_country_entry",
        "actual_passes",
        ["country_code", "entry_time"],
        unique=False,
    )
    op.create_index(
        "ix_actual_passes_satellite_entry",
        "actual_passes",
        ["satellite_id", "entry_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_actual_passes_satellite_entry", table_name="actual_passes")
    op.drop_index("ix_actual_passes_country_entry", table_name="actual_passes")
    op.drop_table("actual_passes")
    op.drop_index("ix_predicted_passes_satellite_entry", table_name="predicted_passes")
    op.drop_index("ix_predicted_passes_country_entry", table_name="predicted_passes")
    op.drop_table("predicted_passes")
    op.drop_index("ix_tle_snapshots_satellite_ingested", table_name="tle_snapshots")
    op.drop_table("tle_snapshots")
    op.drop_table("satellite_bookmarks")
    op.drop_table("passkey_credentials")
    op.drop_table("oauth_accounts")
    op.drop_table("country_bookmarks")
    op.drop_table("users")
    op.drop_table("satellites")
    # ### end Alembic commands ###
